In [ ]:
### Pytorch Tutorial
#### Tensors Basics
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.
It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors.
In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [1]:
import torch

In [2]:
x = torch.tensor(4.0,requires_grad=True)


In [3]:
x

tensor(4., requires_grad=True)

In [5]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

 ### back propogation

In [ ]:
#  y = 2 * x  (which is derivative of input y)

In [7]:
y.backward()

In [10]:
print(x.grad)

tensor(8.)


In [ ]:
#  mmore complex tensors

In [11]:
lst = [[2.,4.,6.],[4.,5.,9.],[8.,3.,9.]]
torch_input = torch.tensor(lst,requires_grad=True)


In [12]:
torch_input

tensor([[2., 4., 6.],
        [4., 5., 9.],
        [8., 3., 9.]], requires_grad=True)

In [13]:
y = torch_input ** 3 + torch_input ** 2

here i/p : y = x **3 + x**2
    derivative= 3x** + 2 + 2x
    
    so for i/p 2, o/p deriavtive==   y = 3 * 2** + 2 + 2 *2
                         y = 16

In [14]:
y

tensor([[ 12.,  80., 252.],
        [ 80., 150., 810.],
        [576.,  36., 810.]], grad_fn=<AddBackward0>)

In [15]:
z = y.sum()

In [16]:
z

tensor(2806., grad_fn=<SumBackward0>)

In [17]:
# back propogation
z.backward()

In [19]:
torch_input.grad

tensor([[ 16.,  56., 120.],
        [ 56.,  85., 261.],
        [208.,  33., 261.]])

###  Creating an ANN using pytorch

In [22]:
import pandas as pd

In [24]:
df = pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [25]:
X=df.drop('Outcome',axis=1).values ### independent features
y=df['Outcome'].values ###dependent features

In [26]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [27]:
#### Libraries From Pytorch
import torch
import torch.nn as nn
import torch.nn.functional as F

In [56]:
# creating tensors (independent features needs to be convert into floattensors)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.longTensor(y_train)
y_test = torch.longTensor(y_test)

In [ ]:
#  create model with pytorch
class ANN_model(nn.Module):
    def __init__(self):   #in init we give ip feature,hidden layers,op featture
        pass
    def forward(self):
        pass

In [57]:
#### Creating Modelwith Pytorch

class ANN_Model(nn.Module):
    def __init__(self,input_features=8,hidden1=20,hidden2=20,out_features=2):
        super().__init__()   #inherite nn.module
        self.f_connected1=nn.Linear(input_features,hidden1)
        self.f_connected2=nn.Linear(hidden1,hidden2)
        self.out=nn.Linear(hidden2,out_features)
    def forward(self,x):
        x=F.relu(self.f_connected1(x))  #calulate gradient descent and forward propogation
        x=F.relu(self.f_connected2(x))
        x=self.out(x)
        return x

In [58]:
####instantiate my ANN_model
torch.manual_seed(20)
model=ANN_Model()

In [59]:
model.parameters

<bound method Module.parameters of ANN_Model(
  (f_connected1): Linear(in_features=8, out_features=20, bias=True)
  (f_connected2): Linear(in_features=20, out_features=20, bias=True)
  (out): Linear(in_features=20, out_features=2, bias=True)
)>

In [60]:
#Backward Propogation 
loss_function=nn.CrossEntropyLoss()  #Define the loss_function
optimizer=torch.optim.Adam(model.parameters(),lr=0.01) #Define the optimizer

In [71]:
# trigger 
epochs=500
final_losses=[]
for i in range(epochs):
    i=i+1
    y_pred=model.forward(X_train)
    loss=loss_function(y_pred, y_train.to(torch.long))
    final_losses.append(loss)
    if i%10==1:
        print("Epoch number: {} and the loss : {}".format(i,loss.item()))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch number: 1 and the loss : 0.8019207119941711
Epoch number: 11 and the loss : 0.6090322136878967
Epoch number: 21 and the loss : 0.5917770862579346
Epoch number: 31 and the loss : 0.5679707527160645
Epoch number: 41 and the loss : 0.5529041886329651
Epoch number: 51 and the loss : 0.5410094857215881
Epoch number: 61 and the loss : 0.5310389995574951
Epoch number: 71 and the loss : 0.5220361351966858
Epoch number: 81 and the loss : 0.5135972499847412
Epoch number: 91 and the loss : 0.5061253905296326
Epoch number: 101 and the loss : 0.498340904712677
Epoch number: 111 and the loss : 0.4960551857948303
Epoch number: 121 and the loss : 0.48286372423171997
Epoch number: 131 and the loss : 0.4755900502204895
Epoch number: 141 and the loss : 0.48198607563972473
Epoch number: 151 and the loss : 0.48064836859703064
Epoch number: 161 and the loss : 0.4706920385360718
Epoch number: 171 and the loss : 0.45908692479133606
Epoch number: 181 and the loss : 0.4507930874824524
Epoch number: 191 an

In [72]:
#### Prediction In X_test data
predictions=[]
with torch.no_grad():
    for i,data in enumerate(X_test):
        y_pred=model(data)
        predictions.append(y_pred.argmax().item())
        print(y_pred.argmax().item())

1
0
0
1
0
0
1
1
0
0
1
1
0
1
0
0
1
0
1
0
1
0
0
0
0
0
0
1
0
0
0
0
0
1
0
1
1
0
0
1
0
0
0
1
1
0
0
0
0
0
0
0
1
0
1
1
0
0
0
0
1
0
0
1
1
1
1
0
0
0
0
0
0
1
1
0
0
1
0
0
0
1
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
1
1
0
0
0
1
0
1
1
0
0
1
0
1
0
1
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
1
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0


In [73]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,predictions)
score


0.7857142857142857

In [74]:
#### New Data
lst1=[9.0, 12.0, 172.0, 41.0, 10.0, 5.6, 0.627, 45.0]

In [75]:
new_data=torch.tensor(lst1)

In [76]:
#### Predict new data using Pytorch
with torch.no_grad():
    print(model(new_data))
    print(model(new_data).argmax().item())

tensor([ 25.4265, -25.6036])
0


ModuleNotFoundError: No module named 'pipreqsnb'